<?php

declare(strict_types=1);

namespace AsceticSoft\Wirebox\Env;

/**
 * Resolves environment variables with 3-level priority:
 *   1. .env.local.php (generated by `composer dump-env`) — PHP array, fastest
 *   2. $_ENV / $_SERVER / getenv() — real system environment
 *   3. .env file — parsed by DotEnvParser, development fallback
 *
 * Also resolves parameter expressions like:
 *   %env(VAR_NAME)%
 *   %env(bool:VAR_NAME)%
 *   %env(int:VAR_NAME)%
 *   %env(float:VAR_NAME)%
 */
final class EnvResolver
{
    /** @var array<string, string> Merged env vars (all 3 levels) */
    private array $resolved = [];

    private bool $loaded = false;

    public function __construct(
        private readonly string $projectDir,
        private readonly DotEnvParser $parser = new DotEnvParser(),
    ) {
    }

    /**
     * Get an env variable value by name.
     */
    public function get(string $name): ?string
    {
        $this->ensureLoaded();

        return $this->resolved[$name] ?? null;
    }

    /**
     * Get all resolved env variables.
     *
     * @return array<string, string>
     */
    public function all(): array
    {
        $this->ensureLoaded();

        return $this->resolved;
    }

    /**
     * Resolve a parameter value, expanding %env(...)% expressions.
     */
    public function resolveParameter(mixed $value): mixed
    {
        if (!\is_string($value)) {
            return $value;
        }

        // Full match: the entire value is %env(...)%
        if (\preg_match('/^%env\(([^)]+)\)%$/', $value, $matches)) {
            return $this->resolveEnvExpression($matches[1]);
        }

        // Partial match: %env(...)% embedded in a larger string
        return \preg_replace_callback('/%env\(([^)]+)\)%/', function (array $matches): string {
            $resolved = $this->resolveEnvExpression($matches[1]);
            return \is_string($resolved) ? $resolved : (string) \var_export($resolved, true);
        }, $value) ?? $value;
    }

    private function resolveEnvExpression(string $expression): mixed
    {
        $this->ensureLoaded();

        // Check for type casting: "type:VAR_NAME"
        if (\str_contains($expression, ':')) {
            [$type, $name] = \explode(':', $expression, 2);
            $raw = $this->resolved[$name] ?? throw new \RuntimeException(
                \sprintf('Environment variable "%s" is not defined.', $name),
            );

            return match ($type) {
                'bool' => \filter_var($raw, \FILTER_VALIDATE_BOOLEAN),
                'int' => (int) $raw,
                'float' => (float) $raw,
                'string' => $raw,
                default => throw new \RuntimeException(\sprintf('Unknown env cast type "%s".', $type)),
            };
        }

        return $this->resolved[$expression] ?? throw new \RuntimeException(
            \sprintf('Environment variable "%s" is not defined.', $expression),
        );
    }

    private function ensureLoaded(): void
    {
        if ($this->loaded) {
            return;
        }

        $this->loaded = true;

        // Level 3 (lowest priority): .env file
        $dotEnvPath = $this->projectDir . '/.env';
        if (\is_file($dotEnvPath)) {
            $this->resolved = $this->parser->parse($dotEnvPath);
        }

        // Level 2: system environment ($_ENV, $_SERVER, getenv)
        // Overwrites .env values
        foreach ($this->resolved as $key => $_) {
            $sysValue = $this->getSystemEnv($key);
            if ($sysValue !== null) {
                $this->resolved[$key] = $sysValue;
            }
        }

        // Also add any system env vars not in .env that are referenced later
        // (they will be resolved on-demand via get())

        // Level 1 (highest priority): .env.local.php (composer dump-env)
        $dumpEnvPath = $this->projectDir . '/.env.local.php';
        if (\is_file($dumpEnvPath)) {
            /** @var mixed $dumpedVars */
            $dumpedVars = require $dumpEnvPath;
            if (\is_array($dumpedVars)) {
                /** @var array<string, string> $dumpedVars */
                $this->resolved = \array_merge($this->resolved, $dumpedVars);
            }
        }
    }

    private function getSystemEnv(string $name): ?string
    {
        if (isset($_ENV[$name]) && \is_scalar($_ENV[$name])) {
            return (string) $_ENV[$name];
        }

        if (isset($_SERVER[$name]) && \is_scalar($_SERVER[$name]) && !\str_starts_with($name, 'HTTP_')) {
            return (string) $_SERVER[$name];
        }

        $value = \getenv($name);
        return $value !== false ? $value : null;
    }
}
